apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: heimdallr-operator-webhook
webhooks:
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: webhook
        namespace: default
        path: /validate
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ6ekNDQVhXZ0F3SUJBZ0lJTGJaekcweXEzbUF3Q2dZSUtvWkl6ajBFQXdJd1FURUpNQWNHQTFVRUJoTUEKTVFrd0J3WURWUVFLRXdBeENUQUhCZ05WQkFzVEFERWVNQndHQTFVRUF4TVZhR1ZwYldSaGJHeHlMVzl3WlhKaApkRzl5SUVOQk1CNFhEVEkwTVRFeU5EQTVNRFV4T1ZvWERUSTJNVEV5TkRBNU1EVXhPVm93SURFZU1Cd0dBMVVFCkF4TVZkMlZpYUc5dmF5NW9aV2x0WkdGc2JISXVjM1pqTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0QKUWdBRTBFMGZuUUlFV1ZzN2o1NVRtZ21nNUl2b2dUTGJwN1BrVVhiRFFUejdabFYzb3VLMEMzbVp2Mkl5aGtodgoxYWk3MnRCa1hCSzhnRzN0dlNoWmQ4bFBaS040TUhZd0RnWURWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNCk1Bb0dDQ3NHQVFVRkJ3TUJNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVLZ09mSVZEK1A1aEQKYnFtYXhrcjFiS1phMHF3d0lBWURWUjBSQkJrd0Y0SVZkMlZpYUc5dmF5NW9aV2x0WkdGc2JISXVjM1pqTUFvRwpDQ3FHU000OUJBTUNBMGdBTUVVQ0lBcVVOeEZqVndXbkIzL2JDZSsvS1Q1RE9VUVhkcDBOYzVYUTRodmkwcElwCkFpRUF4S3VjT09Na2ZSUGE3Tk9McEVHNlBIdndPMjJyald0djRsNkpWOFRjZURrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    failurePolicy: Fail
    name: heimdallr.f110.dev
    rules:
      - apiGroups:
          - etcd.f110.dev
          - proxy.f110.dev
        apiVersions:
          - '*'
        operations:
          - CREATE
          - UPDATE
        resources:
          - '*/*'
    sideEffects: None
