apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: heimdallr-operator-webhook
webhooks:
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: webhook
        namespace: default
        path: /validate
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ1ekNDQVdDZ0F3SUJBZ0lJWkhCNUZWN1N0Ull3Q2dZSUtvWkl6ajBFQXdJd1FURUpNQWNHQTFVRUJoTUEKTVFrd0J3WURWUVFLRXdBeENUQUhCZ05WQkFzVEFERWVNQndHQTFVRUF4TVZhR1ZwYldSaGJHeHlMVzl3WlhKaApkRzl5SUVOQk1CNFhEVEl5TVRFeU1ERTFNamcxTmxvWERUTXlNVEV5TURFMU1qZzFObG93UVRFSk1BY0dBMVVFCkJoTUFNUWt3QndZRFZRUUtFd0F4Q1RBSEJnTlZCQXNUQURFZU1Cd0dBMVVFQXhNVmFHVnBiV1JoYkd4eUxXOXcKWlhKaGRHOXlJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFcmtRNkt1QWJqbHFGUzh0ZApITzN4QThmcVNESmFtV2EwWnRuRVpEeC82WXA1SE1JMlU5NzllcUpJMWZFeHNpVXpGT2JJTEZnL0ZYbHdwWW51CitvcVVzS05DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0dtTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME8KQkJZRUZDb0RueUZRL2orWVEyNnBtc1pLOVd5bVd0S3NNQW9HQ0NxR1NNNDlCQU1DQTBrQU1FWUNJUUNmUXUwVgppWXBMd2hSdzJlalVJY3pOd0hlMDQ3K2Y0SlFUdHRoUHFaaWlId0loQUlldGdqdjYySFZwT0diektKUjhXWmRyCnNEVHVzcFlIS25TN2kvZ3Fsb29aCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    failurePolicy: Fail
    name: heimdallr.f110.dev
    rules:
      - apiGroups:
          - etcd.f110.dev
          - proxy.f110.dev
        apiVersions:
          - '*'
        operations:
          - CREATE
          - UPDATE
        resources:
          - '*/*'
    sideEffects: None
