load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("//:RELEASE.bzl", "PLATFORMS")
load("//build/rules/go:util.bzl", "multiplatform_go_binary")

go_library(
    name = "heim_lib",
    srcs = ["main.go"],
    importpath = "go.f110.dev/heimdallr/cmd/heim",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/cmd",
        "//pkg/cmd/heim",
    ],
)

go_binary(
    name = "heim",
    embed = [":heim_lib"],
    visibility = ["//visibility:public"],
)

multiplatform_go_binary(
    embed = [":heim_lib"],
    name_prefix = "heim",
    platforms = PLATFORMS,
    visibility = ["//visibility:public"],
)
