load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "heim",
    srcs = ["login.go"],
    importpath = "go.f110.dev/heimdallr/pkg/cmd/heim",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/auth/token",
        "//pkg/cmd",
        "//pkg/config/userconfig",
        "@dev_f110_go_xerrors//:xerrors",
    ],
)
