// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pkg/dashboard/dashboard.proto

package dashboard

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MeServiceName is the fully-qualified name of the MeService service.
	MeServiceName = "dashboard.bff.MeService"
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "dashboard.bff.AdminService"
	// CertificateServiceName is the fully-qualified name of the CertificateService service.
	CertificateServiceName = "dashboard.bff.CertificateService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MeServiceGetMeProcedure is the fully-qualified name of the MeService's GetMe RPC.
	MeServiceGetMeProcedure = "/dashboard.bff.MeService/GetMe"
	// MeServiceAddDeviceProcedure is the fully-qualified name of the MeService's AddDevice RPC.
	MeServiceAddDeviceProcedure = "/dashboard.bff.MeService/AddDevice"
	// AdminServiceListUsersProcedure is the fully-qualified name of the AdminService's ListUsers RPC.
	AdminServiceListUsersProcedure = "/dashboard.bff.AdminService/ListUsers"
	// AdminServiceGetUserProcedure is the fully-qualified name of the AdminService's GetUser RPC.
	AdminServiceGetUserProcedure = "/dashboard.bff.AdminService/GetUser"
	// AdminServiceAddUserProcedure is the fully-qualified name of the AdminService's AddUser RPC.
	AdminServiceAddUserProcedure = "/dashboard.bff.AdminService/AddUser"
	// AdminServiceUpdateUserProcedure is the fully-qualified name of the AdminService's UpdateUser RPC.
	AdminServiceUpdateUserProcedure = "/dashboard.bff.AdminService/UpdateUser"
	// AdminServiceDeleteUserProcedure is the fully-qualified name of the AdminService's DeleteUser RPC.
	AdminServiceDeleteUserProcedure = "/dashboard.bff.AdminService/DeleteUser"
	// AdminServiceBecomeMaintainerProcedure is the fully-qualified name of the AdminService's
	// BecomeMaintainer RPC.
	AdminServiceBecomeMaintainerProcedure = "/dashboard.bff.AdminService/BecomeMaintainer"
	// AdminServiceToggleAdminProcedure is the fully-qualified name of the AdminService's ToggleAdmin
	// RPC.
	AdminServiceToggleAdminProcedure = "/dashboard.bff.AdminService/ToggleAdmin"
	// AdminServiceListRolesProcedure is the fully-qualified name of the AdminService's ListRoles RPC.
	AdminServiceListRolesProcedure = "/dashboard.bff.AdminService/ListRoles"
	// AdminServiceListServiceAccountsProcedure is the fully-qualified name of the AdminService's
	// ListServiceAccounts RPC.
	AdminServiceListServiceAccountsProcedure = "/dashboard.bff.AdminService/ListServiceAccounts"
	// AdminServiceCreateServiceAccountProcedure is the fully-qualified name of the AdminService's
	// CreateServiceAccount RPC.
	AdminServiceCreateServiceAccountProcedure = "/dashboard.bff.AdminService/CreateServiceAccount"
	// AdminServiceListServiceAccountTokensProcedure is the fully-qualified name of the AdminService's
	// ListServiceAccountTokens RPC.
	AdminServiceListServiceAccountTokensProcedure = "/dashboard.bff.AdminService/ListServiceAccountTokens"
	// AdminServiceCreateServiceAccountTokenProcedure is the fully-qualified name of the AdminService's
	// CreateServiceAccountToken RPC.
	AdminServiceCreateServiceAccountTokenProcedure = "/dashboard.bff.AdminService/CreateServiceAccountToken"
	// CertificateServiceListCertificatesProcedure is the fully-qualified name of the
	// CertificateService's ListCertificates RPC.
	CertificateServiceListCertificatesProcedure = "/dashboard.bff.CertificateService/ListCertificates"
	// CertificateServiceNewClientCertificateProcedure is the fully-qualified name of the
	// CertificateService's NewClientCertificate RPC.
	CertificateServiceNewClientCertificateProcedure = "/dashboard.bff.CertificateService/NewClientCertificate"
	// CertificateServiceRevokeCertificateProcedure is the fully-qualified name of the
	// CertificateService's RevokeCertificate RPC.
	CertificateServiceRevokeCertificateProcedure = "/dashboard.bff.CertificateService/RevokeCertificate"
	// CertificateServiceListAgentsProcedure is the fully-qualified name of the CertificateService's
	// ListAgents RPC.
	CertificateServiceListAgentsProcedure = "/dashboard.bff.CertificateService/ListAgents"
	// CertificateServiceListAgentBackendsProcedure is the fully-qualified name of the
	// CertificateService's ListAgentBackends RPC.
	CertificateServiceListAgentBackendsProcedure = "/dashboard.bff.CertificateService/ListAgentBackends"
	// CertificateServiceRegisterAgentProcedure is the fully-qualified name of the CertificateService's
	// RegisterAgent RPC.
	CertificateServiceRegisterAgentProcedure = "/dashboard.bff.CertificateService/RegisterAgent"
)

// MeServiceClient is a client for the dashboard.bff.MeService service.
type MeServiceClient interface {
	GetMe(context.Context, *connect.Request[GetMeRequest]) (*connect.Response[GetMeResponse], error)
	AddDevice(context.Context, *connect.Request[AddDeviceRequest]) (*connect.Response[AddDeviceResponse], error)
}

// NewMeServiceClient constructs a client for the dashboard.bff.MeService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	meServiceMethods := File_pkg_dashboard_dashboard_proto.Services().ByName("MeService").Methods()
	return &meServiceClient{
		getMe: connect.NewClient[GetMeRequest, GetMeResponse](
			httpClient,
			baseURL+MeServiceGetMeProcedure,
			connect.WithSchema(meServiceMethods.ByName("GetMe")),
			connect.WithClientOptions(opts...),
		),
		addDevice: connect.NewClient[AddDeviceRequest, AddDeviceResponse](
			httpClient,
			baseURL+MeServiceAddDeviceProcedure,
			connect.WithSchema(meServiceMethods.ByName("AddDevice")),
			connect.WithClientOptions(opts...),
		),
	}
}

// meServiceClient implements MeServiceClient.
type meServiceClient struct {
	getMe     *connect.Client[GetMeRequest, GetMeResponse]
	addDevice *connect.Client[AddDeviceRequest, AddDeviceResponse]
}

// GetMe calls dashboard.bff.MeService.GetMe.
func (c *meServiceClient) GetMe(ctx context.Context, req *connect.Request[GetMeRequest]) (*connect.Response[GetMeResponse], error) {
	return c.getMe.CallUnary(ctx, req)
}

// AddDevice calls dashboard.bff.MeService.AddDevice.
func (c *meServiceClient) AddDevice(ctx context.Context, req *connect.Request[AddDeviceRequest]) (*connect.Response[AddDeviceResponse], error) {
	return c.addDevice.CallUnary(ctx, req)
}

// MeServiceHandler is an implementation of the dashboard.bff.MeService service.
type MeServiceHandler interface {
	GetMe(context.Context, *connect.Request[GetMeRequest]) (*connect.Response[GetMeResponse], error)
	AddDevice(context.Context, *connect.Request[AddDeviceRequest]) (*connect.Response[AddDeviceResponse], error)
}

// NewMeServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMeServiceHandler(svc MeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	meServiceMethods := File_pkg_dashboard_dashboard_proto.Services().ByName("MeService").Methods()
	meServiceGetMeHandler := connect.NewUnaryHandler(
		MeServiceGetMeProcedure,
		svc.GetMe,
		connect.WithSchema(meServiceMethods.ByName("GetMe")),
		connect.WithHandlerOptions(opts...),
	)
	meServiceAddDeviceHandler := connect.NewUnaryHandler(
		MeServiceAddDeviceProcedure,
		svc.AddDevice,
		connect.WithSchema(meServiceMethods.ByName("AddDevice")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dashboard.bff.MeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MeServiceGetMeProcedure:
			meServiceGetMeHandler.ServeHTTP(w, r)
		case MeServiceAddDeviceProcedure:
			meServiceAddDeviceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMeServiceHandler struct{}

func (UnimplementedMeServiceHandler) GetMe(context.Context, *connect.Request[GetMeRequest]) (*connect.Response[GetMeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.MeService.GetMe is not implemented"))
}

func (UnimplementedMeServiceHandler) AddDevice(context.Context, *connect.Request[AddDeviceRequest]) (*connect.Response[AddDeviceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.MeService.AddDevice is not implemented"))
}

// AdminServiceClient is a client for the dashboard.bff.AdminService service.
type AdminServiceClient interface {
	ListUsers(context.Context, *connect.Request[ListUsersRequest]) (*connect.Response[ListUsersResponse], error)
	GetUser(context.Context, *connect.Request[GetUserRequest]) (*connect.Response[GetUserResponse], error)
	AddUser(context.Context, *connect.Request[AddUserRequest]) (*connect.Response[AddUserResponse], error)
	UpdateUser(context.Context, *connect.Request[UpdateUserRequest]) (*connect.Response[UpdateUserResponse], error)
	DeleteUser(context.Context, *connect.Request[DeleteUserRequest]) (*connect.Response[DeleteUserResponse], error)
	BecomeMaintainer(context.Context, *connect.Request[BecomeMaintainerRequest]) (*connect.Response[BecomeMaintainerResponse], error)
	ToggleAdmin(context.Context, *connect.Request[ToggleAdminRequest]) (*connect.Response[ToggleAdminResponse], error)
	ListRoles(context.Context, *connect.Request[ListRolesRequest]) (*connect.Response[ListRolesResponse], error)
	ListServiceAccounts(context.Context, *connect.Request[ListServiceAccountsRequest]) (*connect.Response[ListServiceAccountsResponse], error)
	CreateServiceAccount(context.Context, *connect.Request[CreateServiceAccountRequest]) (*connect.Response[CreateServiceAccountResponse], error)
	ListServiceAccountTokens(context.Context, *connect.Request[ListServiceAccountTokensRequest]) (*connect.Response[ListServiceAccountTokensResponse], error)
	CreateServiceAccountToken(context.Context, *connect.Request[CreateServiceAccountTokenRequest]) (*connect.Response[CreateServiceAccountTokenResponse], error)
}

// NewAdminServiceClient constructs a client for the dashboard.bff.AdminService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminServiceMethods := File_pkg_dashboard_dashboard_proto.Services().ByName("AdminService").Methods()
	return &adminServiceClient{
		listUsers: connect.NewClient[ListUsersRequest, ListUsersResponse](
			httpClient,
			baseURL+AdminServiceListUsersProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		getUser: connect.NewClient[GetUserRequest, GetUserResponse](
			httpClient,
			baseURL+AdminServiceGetUserProcedure,
			connect.WithSchema(adminServiceMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		addUser: connect.NewClient[AddUserRequest, AddUserResponse](
			httpClient,
			baseURL+AdminServiceAddUserProcedure,
			connect.WithSchema(adminServiceMethods.ByName("AddUser")),
			connect.WithClientOptions(opts...),
		),
		updateUser: connect.NewClient[UpdateUserRequest, UpdateUserResponse](
			httpClient,
			baseURL+AdminServiceUpdateUserProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdateUser")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[DeleteUserRequest, DeleteUserResponse](
			httpClient,
			baseURL+AdminServiceDeleteUserProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
		becomeMaintainer: connect.NewClient[BecomeMaintainerRequest, BecomeMaintainerResponse](
			httpClient,
			baseURL+AdminServiceBecomeMaintainerProcedure,
			connect.WithSchema(adminServiceMethods.ByName("BecomeMaintainer")),
			connect.WithClientOptions(opts...),
		),
		toggleAdmin: connect.NewClient[ToggleAdminRequest, ToggleAdminResponse](
			httpClient,
			baseURL+AdminServiceToggleAdminProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ToggleAdmin")),
			connect.WithClientOptions(opts...),
		),
		listRoles: connect.NewClient[ListRolesRequest, ListRolesResponse](
			httpClient,
			baseURL+AdminServiceListRolesProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListRoles")),
			connect.WithClientOptions(opts...),
		),
		listServiceAccounts: connect.NewClient[ListServiceAccountsRequest, ListServiceAccountsResponse](
			httpClient,
			baseURL+AdminServiceListServiceAccountsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListServiceAccounts")),
			connect.WithClientOptions(opts...),
		),
		createServiceAccount: connect.NewClient[CreateServiceAccountRequest, CreateServiceAccountResponse](
			httpClient,
			baseURL+AdminServiceCreateServiceAccountProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CreateServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		listServiceAccountTokens: connect.NewClient[ListServiceAccountTokensRequest, ListServiceAccountTokensResponse](
			httpClient,
			baseURL+AdminServiceListServiceAccountTokensProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListServiceAccountTokens")),
			connect.WithClientOptions(opts...),
		),
		createServiceAccountToken: connect.NewClient[CreateServiceAccountTokenRequest, CreateServiceAccountTokenResponse](
			httpClient,
			baseURL+AdminServiceCreateServiceAccountTokenProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CreateServiceAccountToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	listUsers                 *connect.Client[ListUsersRequest, ListUsersResponse]
	getUser                   *connect.Client[GetUserRequest, GetUserResponse]
	addUser                   *connect.Client[AddUserRequest, AddUserResponse]
	updateUser                *connect.Client[UpdateUserRequest, UpdateUserResponse]
	deleteUser                *connect.Client[DeleteUserRequest, DeleteUserResponse]
	becomeMaintainer          *connect.Client[BecomeMaintainerRequest, BecomeMaintainerResponse]
	toggleAdmin               *connect.Client[ToggleAdminRequest, ToggleAdminResponse]
	listRoles                 *connect.Client[ListRolesRequest, ListRolesResponse]
	listServiceAccounts       *connect.Client[ListServiceAccountsRequest, ListServiceAccountsResponse]
	createServiceAccount      *connect.Client[CreateServiceAccountRequest, CreateServiceAccountResponse]
	listServiceAccountTokens  *connect.Client[ListServiceAccountTokensRequest, ListServiceAccountTokensResponse]
	createServiceAccountToken *connect.Client[CreateServiceAccountTokenRequest, CreateServiceAccountTokenResponse]
}

// ListUsers calls dashboard.bff.AdminService.ListUsers.
func (c *adminServiceClient) ListUsers(ctx context.Context, req *connect.Request[ListUsersRequest]) (*connect.Response[ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// GetUser calls dashboard.bff.AdminService.GetUser.
func (c *adminServiceClient) GetUser(ctx context.Context, req *connect.Request[GetUserRequest]) (*connect.Response[GetUserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// AddUser calls dashboard.bff.AdminService.AddUser.
func (c *adminServiceClient) AddUser(ctx context.Context, req *connect.Request[AddUserRequest]) (*connect.Response[AddUserResponse], error) {
	return c.addUser.CallUnary(ctx, req)
}

// UpdateUser calls dashboard.bff.AdminService.UpdateUser.
func (c *adminServiceClient) UpdateUser(ctx context.Context, req *connect.Request[UpdateUserRequest]) (*connect.Response[UpdateUserResponse], error) {
	return c.updateUser.CallUnary(ctx, req)
}

// DeleteUser calls dashboard.bff.AdminService.DeleteUser.
func (c *adminServiceClient) DeleteUser(ctx context.Context, req *connect.Request[DeleteUserRequest]) (*connect.Response[DeleteUserResponse], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// BecomeMaintainer calls dashboard.bff.AdminService.BecomeMaintainer.
func (c *adminServiceClient) BecomeMaintainer(ctx context.Context, req *connect.Request[BecomeMaintainerRequest]) (*connect.Response[BecomeMaintainerResponse], error) {
	return c.becomeMaintainer.CallUnary(ctx, req)
}

// ToggleAdmin calls dashboard.bff.AdminService.ToggleAdmin.
func (c *adminServiceClient) ToggleAdmin(ctx context.Context, req *connect.Request[ToggleAdminRequest]) (*connect.Response[ToggleAdminResponse], error) {
	return c.toggleAdmin.CallUnary(ctx, req)
}

// ListRoles calls dashboard.bff.AdminService.ListRoles.
func (c *adminServiceClient) ListRoles(ctx context.Context, req *connect.Request[ListRolesRequest]) (*connect.Response[ListRolesResponse], error) {
	return c.listRoles.CallUnary(ctx, req)
}

// ListServiceAccounts calls dashboard.bff.AdminService.ListServiceAccounts.
func (c *adminServiceClient) ListServiceAccounts(ctx context.Context, req *connect.Request[ListServiceAccountsRequest]) (*connect.Response[ListServiceAccountsResponse], error) {
	return c.listServiceAccounts.CallUnary(ctx, req)
}

// CreateServiceAccount calls dashboard.bff.AdminService.CreateServiceAccount.
func (c *adminServiceClient) CreateServiceAccount(ctx context.Context, req *connect.Request[CreateServiceAccountRequest]) (*connect.Response[CreateServiceAccountResponse], error) {
	return c.createServiceAccount.CallUnary(ctx, req)
}

// ListServiceAccountTokens calls dashboard.bff.AdminService.ListServiceAccountTokens.
func (c *adminServiceClient) ListServiceAccountTokens(ctx context.Context, req *connect.Request[ListServiceAccountTokensRequest]) (*connect.Response[ListServiceAccountTokensResponse], error) {
	return c.listServiceAccountTokens.CallUnary(ctx, req)
}

// CreateServiceAccountToken calls dashboard.bff.AdminService.CreateServiceAccountToken.
func (c *adminServiceClient) CreateServiceAccountToken(ctx context.Context, req *connect.Request[CreateServiceAccountTokenRequest]) (*connect.Response[CreateServiceAccountTokenResponse], error) {
	return c.createServiceAccountToken.CallUnary(ctx, req)
}

// AdminServiceHandler is an implementation of the dashboard.bff.AdminService service.
type AdminServiceHandler interface {
	ListUsers(context.Context, *connect.Request[ListUsersRequest]) (*connect.Response[ListUsersResponse], error)
	GetUser(context.Context, *connect.Request[GetUserRequest]) (*connect.Response[GetUserResponse], error)
	AddUser(context.Context, *connect.Request[AddUserRequest]) (*connect.Response[AddUserResponse], error)
	UpdateUser(context.Context, *connect.Request[UpdateUserRequest]) (*connect.Response[UpdateUserResponse], error)
	DeleteUser(context.Context, *connect.Request[DeleteUserRequest]) (*connect.Response[DeleteUserResponse], error)
	BecomeMaintainer(context.Context, *connect.Request[BecomeMaintainerRequest]) (*connect.Response[BecomeMaintainerResponse], error)
	ToggleAdmin(context.Context, *connect.Request[ToggleAdminRequest]) (*connect.Response[ToggleAdminResponse], error)
	ListRoles(context.Context, *connect.Request[ListRolesRequest]) (*connect.Response[ListRolesResponse], error)
	ListServiceAccounts(context.Context, *connect.Request[ListServiceAccountsRequest]) (*connect.Response[ListServiceAccountsResponse], error)
	CreateServiceAccount(context.Context, *connect.Request[CreateServiceAccountRequest]) (*connect.Response[CreateServiceAccountResponse], error)
	ListServiceAccountTokens(context.Context, *connect.Request[ListServiceAccountTokensRequest]) (*connect.Response[ListServiceAccountTokensResponse], error)
	CreateServiceAccountToken(context.Context, *connect.Request[CreateServiceAccountTokenRequest]) (*connect.Response[CreateServiceAccountTokenResponse], error)
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminServiceMethods := File_pkg_dashboard_dashboard_proto.Services().ByName("AdminService").Methods()
	adminServiceListUsersHandler := connect.NewUnaryHandler(
		AdminServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(adminServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceGetUserHandler := connect.NewUnaryHandler(
		AdminServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(adminServiceMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceAddUserHandler := connect.NewUnaryHandler(
		AdminServiceAddUserProcedure,
		svc.AddUser,
		connect.WithSchema(adminServiceMethods.ByName("AddUser")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdateUserHandler := connect.NewUnaryHandler(
		AdminServiceUpdateUserProcedure,
		svc.UpdateUser,
		connect.WithSchema(adminServiceMethods.ByName("UpdateUser")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteUserHandler := connect.NewUnaryHandler(
		AdminServiceDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(adminServiceMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceBecomeMaintainerHandler := connect.NewUnaryHandler(
		AdminServiceBecomeMaintainerProcedure,
		svc.BecomeMaintainer,
		connect.WithSchema(adminServiceMethods.ByName("BecomeMaintainer")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceToggleAdminHandler := connect.NewUnaryHandler(
		AdminServiceToggleAdminProcedure,
		svc.ToggleAdmin,
		connect.WithSchema(adminServiceMethods.ByName("ToggleAdmin")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListRolesHandler := connect.NewUnaryHandler(
		AdminServiceListRolesProcedure,
		svc.ListRoles,
		connect.WithSchema(adminServiceMethods.ByName("ListRoles")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListServiceAccountsHandler := connect.NewUnaryHandler(
		AdminServiceListServiceAccountsProcedure,
		svc.ListServiceAccounts,
		connect.WithSchema(adminServiceMethods.ByName("ListServiceAccounts")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceCreateServiceAccountHandler := connect.NewUnaryHandler(
		AdminServiceCreateServiceAccountProcedure,
		svc.CreateServiceAccount,
		connect.WithSchema(adminServiceMethods.ByName("CreateServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListServiceAccountTokensHandler := connect.NewUnaryHandler(
		AdminServiceListServiceAccountTokensProcedure,
		svc.ListServiceAccountTokens,
		connect.WithSchema(adminServiceMethods.ByName("ListServiceAccountTokens")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceCreateServiceAccountTokenHandler := connect.NewUnaryHandler(
		AdminServiceCreateServiceAccountTokenProcedure,
		svc.CreateServiceAccountToken,
		connect.WithSchema(adminServiceMethods.ByName("CreateServiceAccountToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dashboard.bff.AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServiceListUsersProcedure:
			adminServiceListUsersHandler.ServeHTTP(w, r)
		case AdminServiceGetUserProcedure:
			adminServiceGetUserHandler.ServeHTTP(w, r)
		case AdminServiceAddUserProcedure:
			adminServiceAddUserHandler.ServeHTTP(w, r)
		case AdminServiceUpdateUserProcedure:
			adminServiceUpdateUserHandler.ServeHTTP(w, r)
		case AdminServiceDeleteUserProcedure:
			adminServiceDeleteUserHandler.ServeHTTP(w, r)
		case AdminServiceBecomeMaintainerProcedure:
			adminServiceBecomeMaintainerHandler.ServeHTTP(w, r)
		case AdminServiceToggleAdminProcedure:
			adminServiceToggleAdminHandler.ServeHTTP(w, r)
		case AdminServiceListRolesProcedure:
			adminServiceListRolesHandler.ServeHTTP(w, r)
		case AdminServiceListServiceAccountsProcedure:
			adminServiceListServiceAccountsHandler.ServeHTTP(w, r)
		case AdminServiceCreateServiceAccountProcedure:
			adminServiceCreateServiceAccountHandler.ServeHTTP(w, r)
		case AdminServiceListServiceAccountTokensProcedure:
			adminServiceListServiceAccountTokensHandler.ServeHTTP(w, r)
		case AdminServiceCreateServiceAccountTokenProcedure:
			adminServiceCreateServiceAccountTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) ListUsers(context.Context, *connect.Request[ListUsersRequest]) (*connect.Response[ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.AdminService.ListUsers is not implemented"))
}

func (UnimplementedAdminServiceHandler) GetUser(context.Context, *connect.Request[GetUserRequest]) (*connect.Response[GetUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.AdminService.GetUser is not implemented"))
}

func (UnimplementedAdminServiceHandler) AddUser(context.Context, *connect.Request[AddUserRequest]) (*connect.Response[AddUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.AdminService.AddUser is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdateUser(context.Context, *connect.Request[UpdateUserRequest]) (*connect.Response[UpdateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.AdminService.UpdateUser is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteUser(context.Context, *connect.Request[DeleteUserRequest]) (*connect.Response[DeleteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.AdminService.DeleteUser is not implemented"))
}

func (UnimplementedAdminServiceHandler) BecomeMaintainer(context.Context, *connect.Request[BecomeMaintainerRequest]) (*connect.Response[BecomeMaintainerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.AdminService.BecomeMaintainer is not implemented"))
}

func (UnimplementedAdminServiceHandler) ToggleAdmin(context.Context, *connect.Request[ToggleAdminRequest]) (*connect.Response[ToggleAdminResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.AdminService.ToggleAdmin is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListRoles(context.Context, *connect.Request[ListRolesRequest]) (*connect.Response[ListRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.AdminService.ListRoles is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListServiceAccounts(context.Context, *connect.Request[ListServiceAccountsRequest]) (*connect.Response[ListServiceAccountsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.AdminService.ListServiceAccounts is not implemented"))
}

func (UnimplementedAdminServiceHandler) CreateServiceAccount(context.Context, *connect.Request[CreateServiceAccountRequest]) (*connect.Response[CreateServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.AdminService.CreateServiceAccount is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListServiceAccountTokens(context.Context, *connect.Request[ListServiceAccountTokensRequest]) (*connect.Response[ListServiceAccountTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.AdminService.ListServiceAccountTokens is not implemented"))
}

func (UnimplementedAdminServiceHandler) CreateServiceAccountToken(context.Context, *connect.Request[CreateServiceAccountTokenRequest]) (*connect.Response[CreateServiceAccountTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.AdminService.CreateServiceAccountToken is not implemented"))
}

// CertificateServiceClient is a client for the dashboard.bff.CertificateService service.
type CertificateServiceClient interface {
	ListCertificates(context.Context, *connect.Request[ListCertificatesRequest]) (*connect.Response[ListCertificatesResponse], error)
	NewClientCertificate(context.Context, *connect.Request[NewClientCertificateRequest]) (*connect.Response[NewClientCertificateResponse], error)
	RevokeCertificate(context.Context, *connect.Request[RevokeCertificateRequest]) (*connect.Response[RevokeCertificateResponse], error)
	ListAgents(context.Context, *connect.Request[ListAgentsRequest]) (*connect.Response[ListAgentsResponse], error)
	ListAgentBackends(context.Context, *connect.Request[ListAgentBackendsRequest]) (*connect.Response[ListAgentBackendsResponse], error)
	RegisterAgent(context.Context, *connect.Request[RegisterAgentRequest]) (*connect.Response[RegisterAgentResponse], error)
}

// NewCertificateServiceClient constructs a client for the dashboard.bff.CertificateService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCertificateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CertificateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	certificateServiceMethods := File_pkg_dashboard_dashboard_proto.Services().ByName("CertificateService").Methods()
	return &certificateServiceClient{
		listCertificates: connect.NewClient[ListCertificatesRequest, ListCertificatesResponse](
			httpClient,
			baseURL+CertificateServiceListCertificatesProcedure,
			connect.WithSchema(certificateServiceMethods.ByName("ListCertificates")),
			connect.WithClientOptions(opts...),
		),
		newClientCertificate: connect.NewClient[NewClientCertificateRequest, NewClientCertificateResponse](
			httpClient,
			baseURL+CertificateServiceNewClientCertificateProcedure,
			connect.WithSchema(certificateServiceMethods.ByName("NewClientCertificate")),
			connect.WithClientOptions(opts...),
		),
		revokeCertificate: connect.NewClient[RevokeCertificateRequest, RevokeCertificateResponse](
			httpClient,
			baseURL+CertificateServiceRevokeCertificateProcedure,
			connect.WithSchema(certificateServiceMethods.ByName("RevokeCertificate")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[ListAgentsRequest, ListAgentsResponse](
			httpClient,
			baseURL+CertificateServiceListAgentsProcedure,
			connect.WithSchema(certificateServiceMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		listAgentBackends: connect.NewClient[ListAgentBackendsRequest, ListAgentBackendsResponse](
			httpClient,
			baseURL+CertificateServiceListAgentBackendsProcedure,
			connect.WithSchema(certificateServiceMethods.ByName("ListAgentBackends")),
			connect.WithClientOptions(opts...),
		),
		registerAgent: connect.NewClient[RegisterAgentRequest, RegisterAgentResponse](
			httpClient,
			baseURL+CertificateServiceRegisterAgentProcedure,
			connect.WithSchema(certificateServiceMethods.ByName("RegisterAgent")),
			connect.WithClientOptions(opts...),
		),
	}
}

// certificateServiceClient implements CertificateServiceClient.
type certificateServiceClient struct {
	listCertificates     *connect.Client[ListCertificatesRequest, ListCertificatesResponse]
	newClientCertificate *connect.Client[NewClientCertificateRequest, NewClientCertificateResponse]
	revokeCertificate    *connect.Client[RevokeCertificateRequest, RevokeCertificateResponse]
	listAgents           *connect.Client[ListAgentsRequest, ListAgentsResponse]
	listAgentBackends    *connect.Client[ListAgentBackendsRequest, ListAgentBackendsResponse]
	registerAgent        *connect.Client[RegisterAgentRequest, RegisterAgentResponse]
}

// ListCertificates calls dashboard.bff.CertificateService.ListCertificates.
func (c *certificateServiceClient) ListCertificates(ctx context.Context, req *connect.Request[ListCertificatesRequest]) (*connect.Response[ListCertificatesResponse], error) {
	return c.listCertificates.CallUnary(ctx, req)
}

// NewClientCertificate calls dashboard.bff.CertificateService.NewClientCertificate.
func (c *certificateServiceClient) NewClientCertificate(ctx context.Context, req *connect.Request[NewClientCertificateRequest]) (*connect.Response[NewClientCertificateResponse], error) {
	return c.newClientCertificate.CallUnary(ctx, req)
}

// RevokeCertificate calls dashboard.bff.CertificateService.RevokeCertificate.
func (c *certificateServiceClient) RevokeCertificate(ctx context.Context, req *connect.Request[RevokeCertificateRequest]) (*connect.Response[RevokeCertificateResponse], error) {
	return c.revokeCertificate.CallUnary(ctx, req)
}

// ListAgents calls dashboard.bff.CertificateService.ListAgents.
func (c *certificateServiceClient) ListAgents(ctx context.Context, req *connect.Request[ListAgentsRequest]) (*connect.Response[ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// ListAgentBackends calls dashboard.bff.CertificateService.ListAgentBackends.
func (c *certificateServiceClient) ListAgentBackends(ctx context.Context, req *connect.Request[ListAgentBackendsRequest]) (*connect.Response[ListAgentBackendsResponse], error) {
	return c.listAgentBackends.CallUnary(ctx, req)
}

// RegisterAgent calls dashboard.bff.CertificateService.RegisterAgent.
func (c *certificateServiceClient) RegisterAgent(ctx context.Context, req *connect.Request[RegisterAgentRequest]) (*connect.Response[RegisterAgentResponse], error) {
	return c.registerAgent.CallUnary(ctx, req)
}

// CertificateServiceHandler is an implementation of the dashboard.bff.CertificateService service.
type CertificateServiceHandler interface {
	ListCertificates(context.Context, *connect.Request[ListCertificatesRequest]) (*connect.Response[ListCertificatesResponse], error)
	NewClientCertificate(context.Context, *connect.Request[NewClientCertificateRequest]) (*connect.Response[NewClientCertificateResponse], error)
	RevokeCertificate(context.Context, *connect.Request[RevokeCertificateRequest]) (*connect.Response[RevokeCertificateResponse], error)
	ListAgents(context.Context, *connect.Request[ListAgentsRequest]) (*connect.Response[ListAgentsResponse], error)
	ListAgentBackends(context.Context, *connect.Request[ListAgentBackendsRequest]) (*connect.Response[ListAgentBackendsResponse], error)
	RegisterAgent(context.Context, *connect.Request[RegisterAgentRequest]) (*connect.Response[RegisterAgentResponse], error)
}

// NewCertificateServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCertificateServiceHandler(svc CertificateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	certificateServiceMethods := File_pkg_dashboard_dashboard_proto.Services().ByName("CertificateService").Methods()
	certificateServiceListCertificatesHandler := connect.NewUnaryHandler(
		CertificateServiceListCertificatesProcedure,
		svc.ListCertificates,
		connect.WithSchema(certificateServiceMethods.ByName("ListCertificates")),
		connect.WithHandlerOptions(opts...),
	)
	certificateServiceNewClientCertificateHandler := connect.NewUnaryHandler(
		CertificateServiceNewClientCertificateProcedure,
		svc.NewClientCertificate,
		connect.WithSchema(certificateServiceMethods.ByName("NewClientCertificate")),
		connect.WithHandlerOptions(opts...),
	)
	certificateServiceRevokeCertificateHandler := connect.NewUnaryHandler(
		CertificateServiceRevokeCertificateProcedure,
		svc.RevokeCertificate,
		connect.WithSchema(certificateServiceMethods.ByName("RevokeCertificate")),
		connect.WithHandlerOptions(opts...),
	)
	certificateServiceListAgentsHandler := connect.NewUnaryHandler(
		CertificateServiceListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(certificateServiceMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	certificateServiceListAgentBackendsHandler := connect.NewUnaryHandler(
		CertificateServiceListAgentBackendsProcedure,
		svc.ListAgentBackends,
		connect.WithSchema(certificateServiceMethods.ByName("ListAgentBackends")),
		connect.WithHandlerOptions(opts...),
	)
	certificateServiceRegisterAgentHandler := connect.NewUnaryHandler(
		CertificateServiceRegisterAgentProcedure,
		svc.RegisterAgent,
		connect.WithSchema(certificateServiceMethods.ByName("RegisterAgent")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dashboard.bff.CertificateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CertificateServiceListCertificatesProcedure:
			certificateServiceListCertificatesHandler.ServeHTTP(w, r)
		case CertificateServiceNewClientCertificateProcedure:
			certificateServiceNewClientCertificateHandler.ServeHTTP(w, r)
		case CertificateServiceRevokeCertificateProcedure:
			certificateServiceRevokeCertificateHandler.ServeHTTP(w, r)
		case CertificateServiceListAgentsProcedure:
			certificateServiceListAgentsHandler.ServeHTTP(w, r)
		case CertificateServiceListAgentBackendsProcedure:
			certificateServiceListAgentBackendsHandler.ServeHTTP(w, r)
		case CertificateServiceRegisterAgentProcedure:
			certificateServiceRegisterAgentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCertificateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCertificateServiceHandler struct{}

func (UnimplementedCertificateServiceHandler) ListCertificates(context.Context, *connect.Request[ListCertificatesRequest]) (*connect.Response[ListCertificatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.CertificateService.ListCertificates is not implemented"))
}

func (UnimplementedCertificateServiceHandler) NewClientCertificate(context.Context, *connect.Request[NewClientCertificateRequest]) (*connect.Response[NewClientCertificateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.CertificateService.NewClientCertificate is not implemented"))
}

func (UnimplementedCertificateServiceHandler) RevokeCertificate(context.Context, *connect.Request[RevokeCertificateRequest]) (*connect.Response[RevokeCertificateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.CertificateService.RevokeCertificate is not implemented"))
}

func (UnimplementedCertificateServiceHandler) ListAgents(context.Context, *connect.Request[ListAgentsRequest]) (*connect.Response[ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.CertificateService.ListAgents is not implemented"))
}

func (UnimplementedCertificateServiceHandler) ListAgentBackends(context.Context, *connect.Request[ListAgentBackendsRequest]) (*connect.Response[ListAgentBackendsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.CertificateService.ListAgentBackends is not implemented"))
}

func (UnimplementedCertificateServiceHandler) RegisterAgent(context.Context, *connect.Request[RegisterAgentRequest]) (*connect.Response[RegisterAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dashboard.bff.CertificateService.RegisterAgent is not implemented"))
}
