apiVersion: proxy.f110.dev/v1alpha1
kind: Proxy
metadata:
  name: proxy-sample
spec:
  replicas: 3
  version: v0.10.1
  domain: local-proxy.f110.dev
  port: 443
  organization: test
  administratorUnit: super
  backendSelector:
    matchLabels:
      instance: proxy-sample
  roleSelector:
    matchLabels:
      instance: proxy-sample
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
  identityProvider:
    provider: google
    clientId: 70353433905-pqk31pc51d76hnk225tssjh9mkaof3da.apps.googleusercontent.com
    clientSecretRef:
      name: client-secret
      key: client_secret
    redirectUrl: https://local-proxy.f110.dev:4000/auth/callback
  rootUsers:
    - fmhrit@gmail.com
    - root@f110.dev
  session:
    type: secure_cookie
    keySecretRef:
      name: cookie-secret
  monitor:
    prometheusMonitoring: true
    labels:
      k8s-app: etcd
  dataStore:
    etcd:
      version: v3.4.9
      defragment:
        schedule: "18 13 * * *"
  development: true
#  backup:
#    intervalInSecond: 60
#    maxBackups: 10
#    bucket: proxy
#    path: backup
#    credentialRef:
#      name: backup-credential
#    endpoint: http://object-storage-hl-svc.default.svc.cluster.local:9000
