apiVersion: proxy.f110.dev/v1alpha2
kind: Backend
metadata:
  name: backend-sample
  labels:
    instance: proxy-sample
spec:
  layer: example
  http:
    - path: /
      upstream: http://localhost:4502
  permissions:
    - name: all
      locations:
        - get: /
#    - name: github
#      webhook: "github"
#      webhookConfiguration:
#        github:
#          repositories: ["f110/sandbox"]
#          credentialSecretName: githubapp
#          appIdKey: appid
#          installationIdKey: installationid
#          privateKeyKey: privatekey.pem
#          contentType: json
#          path: /webhook
#          events: ["push"]
---
apiVersion: proxy.f110.dev/v1alpha1
kind: Backend
metadata:
  name: backend-agent-sample
  labels:
    instance: proxy-sample
spec:
  layer: agent
  upstream: http://localhost:4502
  agent: true
  permissions:
    - name: all
      locations:
        - get: /
---
apiVersion: proxy.f110.dev/v1alpha1
kind: Backend
metadata:
  name: backend-fqdn
  labels:
    instance: proxy-sample
spec:
  fqdn: short.f110.dev
  upstream: http://localhost:4502
  permissions:
    - name: all
      locations:
        - any: /
---
apiVersion: proxy.f110.dev/v1alpha1
kind: Backend
metadata:
  name: backend-socket
  labels:
    instance: proxy-sample
spec:
  upstream: tcp://localhost:4502
  socketTimeout: 1m
  maxSessionDuration: 1m
  permissions:
    - name: all
      locations:
        - any: /
---
apiVersion: proxy.f110.dev/v1alpha1
kind: Backend
metadata:
  name: backend-kubernetes
  labels:
    instance: proxy-sample
spec:
  serviceSelector:
    namespace: default
    matchLabels:
      provider: kubernetes
    port: https
    scheme: https
  permissions:
    - name: all
      locations:
        - any: /